danliris/com-danliris-service-finance-accounting

.codecov.yml
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/PurchasingDispositionExpedition/IPurchasingDispositionExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/JournalTransaction/JournalTransactionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/PurchasingDispositionExpedition/PurchasingDispositionExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Enums/CreditorAccountEnum.cs
Com.Danliris.Service.Finance.Accounting.Lib/Enums/Expedition/ExpeditionPosition.cs
Com.Danliris.Service.Finance.Accounting.Lib/Enums/Master/COACategoryEnum.cs
Com.Danliris.Service.Finance.Accounting.Lib/Helpers/APIEndpoint.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/PurchasingDispositionExpedition/PurchasingDispositionExpeditionModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/Services/HttpClientService/HttpClientService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Utilities/ServiceValidationException.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/JournalTransaction/JournalTransactionViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/PurchasingDispositionAcceptance/PurchasingDispositionAcceptanceItemViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/PurchasingDispositionAcceptance/PurchasingDispositionAcceptanceViewModel.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/Masters/COAControllerTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/PurchasingDIspositionAcceptance/PurchasingDispositionAcceptanceControllerTest.cs
Com.Danliris.Service.Finance.Accounting.Test/DataUtils/PurchasingDispositionExpedition/PurchasingDispositionExpeditionDataUtil.cs
Com.Danliris.Service.Finance.Accounting.Test/Helpers/HttpClientFailTestService.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/JournalTransaction/JournalTransactionServiceTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/PurchasingDispositionExpedition/PurchasingDispositionExpeditionServiceTest.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/Master/COAController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/PurchasingDispositionAcceptance/PurchasingDispositionAcceptanceController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Startup.cs

Reverts danliris/com-danliris-service-finance-accounting#40

Revert "Revert "Dev to UAT 05 Desember 2018""

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs

[UPDATE] Fix Bug VB Realization Verification

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs

[UPDATE] Fix Bug Realization Verification Reports

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs

- Fix query select data on Reject
- Fix query select data on ReadVerification

[UPDATE] Fix Bug Query VB Realization Verification

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/VBRealizationDocumentNonPO/VBRealizationDocumentNonPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRealizationDocument/VBRealizationDocumentExpenditureItemModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRealizationDocumentNonPOPDFInklaringTemplate.cs

Fix pdf and update functionality on VB Realization Document Non PO Inklaring

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentWithPODto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentWithPOFormDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20200928070157_Add_TypePurchasing_VBRequestDocument.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20200928070157_Add_TypePurchasing_VBRequestDocument.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRequestDocument/VBRequestDocumentModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRequestDocumentNonPOPDFTemplate.cs

- add TypePurchasing on VBRequestDocument with PO

[UPDATE] Enhance VB Request Document with PO

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentService.cs

- enhance documentNo on create VB withPO

[UPDATE] Fix VB Request Document with PO

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/VBRealizationDocumentNonPO/VBRealizationDocumentNonPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/FormDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/VBRealizationWithPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/ReportDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentService.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/VBRealizationDocumentNonPO/VBRealizationDocumentNonPOServiceTest.cs

- VB Request Document
- VB Realization With PO
- VB Realization non PO

[UPDATE] Enhance Document Number

---

Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRealizationDocumentNonPOPDFInklaringTemplate.cs
Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRealizationDocumentNonPOPDFTemplate.cs
Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRealizationDocumentPOPDFTemplate.cs
Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRequestDocumentNonPOPDFTemplate.cs
Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRequestDocumentWithPOPDFTemplate.cs
Com.Danliris.Service.Finance.Accounting.Test/DataUtils/RealizationVBWIthPO/RealizationVbWithPODataUtil.cs

Enhancement PDF Templete - VBRequest & VBRealization

Enhancement PDF Templete - VBRequest & VBRealization

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/BudgetCashflow/ExcelGenerator/CashflowDivisionExcelGenerator.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/BudgetCashflow/ExcelGenerator/CashflowUnitExcelGenerator.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/BudgetCashflow/PdfGenerator/CashflowDivisionPdfGenerator.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/BudgetCashflow/PdfGenerator/CashflowUnitPdfGenerator.cs

- Judul periode yang benar : Periode Bulan Februari 2021 (tidak pakai “S.D”)
- Untuk Layout Report budget cashflow unit mohon disetting portrait saja dan untuk lebar kolom menyesuaikan
- Untuk setiap judul mata anggaran seperti Pendapatan Operasional,Pendapatan Operasional lain-lain,HPP/Biaya Produksi , Total dan sub total dicetak tebal
- Mohon diberikan separator angka disetiap nominal angka dengan dua digit dibelakang koma
- Untuk tampilan tulisan Operating Acitivities,Investing Activities,Financing Activities ,Cash In,Cash Out,Saldo Awal.Saldo Akhir,Saldo Real Kas,Rate,Selisih dan Total Surplus/Defisit Equivalent di cetak tebal

Feedback Ines Cetakan

---

Com.Danliris.Service.Finance.Accounting.Lib/AutoMapperProfiles/MemoGarmentPurchasing/MemoGarmentPurchasingProfile.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/MemoGarmentPurchasing/MemoGarmentPurchasingService.cs
Com.Danliris.Service.Finance.Accounting.Lib/FinanceDbContext.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20210331043528_Update_MemoGarmentPurchasingDetails.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20210331043528_Update_MemoGarmentPurchasingDetails.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/MemoGarmentPurchasing/MemoGarmentPurchasingModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/MemoGarmentPurchasing/MemoGarmentPurchasingViewModel.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Com.Danliris.Service.Finance.Accounting.WebApi.csproj
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/MemoGarmentPurchasing/MemoGarmentPurchasingContoller.cs

[SOLVE] Conflict on Local Update
[UPDATE] Add Migration UpdateMemoGarmentPurchasingDetails

[UPDATE] Add API RUD MemoGarmentPurchasing

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CreditorAccount/CreditorAccountService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Helpers/Excel.cs
Com.Danliris.Service.Finance.Accounting.Test/Helpers/ExcelTest.cs

Bug Fix Menambahkan Nama supplier di excel Kartu Hutang

Bug Fix Kartu Hutang

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/DailyBankTransaction/DailyBankTransactionService.cs

Data yang muncul di urutin berdasarkan tanggal

Laporan mutasi bank

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/VBRealizationWithPODto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/VBRealizationWithPOService.cs

Penambahan Remark sebagai kolom keterangan di UI VB With PO

Enhance CRUD Backend Realisasi VB dengan PO

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentService.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/Memo/MemoServiceTest.cs

Bug Fix PO Eksternal OB

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/DailyBankTransaction/DailyBankTransactionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/VBRealizationExpeditionController.cs

Bug Fix Filter Tanggal Ekspedisi Realisasi VB dan bug fix selisih vs mutasi

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/OthersExpenditureProofDocument/OthersExpenditureProofDocumentService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/PaymentDispositionNote/PaymentDispositionNoteService.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/OthersExpenditureProofDocument/OthersExpenditureProofDocumentServiceTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/PaymentDispositionNote/PaymentDispositionNoteServiceTest.cs

fix BI Currency in Bukti Permbayaran Disposisi dan Bukti Pengeluaran bank lain-lain

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/DailyBankTransaction/DailyBankTransactionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/JournalTransaction/AutoJournalService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/JournalTransaction/IAutoJournalService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20220215090843_enhance_bankCharge_JournalTrnsactions.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20220215090843_enhance_bankCharge_JournalTrnsactions.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20220215094545_enhance_sourceFunding_JournalTransactions.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20220215094545_enhance_sourceFunding_JournalTransactions.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/DailyBankTransaction/DailyBankTransactionModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/DailyBankTransaction/DailyBankTransactionViewModel.cs
Com.Danliris.Service.Finance.Accounting.Test/DataUtils/DailyBankTransaction/DailyBankTransactionDataUtil.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/DailyBankTransaction/DailyBankTransactionServiceTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/JournalTransaction/AutoJournalServiceTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/OthersExpenditureProofDocument/Helper/AutoJournalServiceTestHelper.cs

Posting generate JournalTransactions

enhance DailyBankTransaction

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentService.cs
Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRequestDocumentWithPOPDFTemplate.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/VbWithPORequest/VbWithPORequestDetailViewModel.cs
Com.Danliris.Service.Finance.Accounting.Test/DataUtils/VbWithPORequest/VbWithPORequestDataUtil.cs

Enhance - VB With PO PDF

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionPaymentReport/GarmentDispositionPaymentReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionPaymentReport/IGarmentDispositionPaymentReportService.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/GarmentDispositionExpeditionController.cs

enhance-payment-disposition-report

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionPaymentReport/GarmentDispositionPaymentReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionPaymentReport/IGarmentDispositionPaymentReportService.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/GarmentDispositionExpedition/GarmentDispositionExpeditionControllerTest.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/GarmentDispositionExpeditionController.cs

Add Filter External Purchase Order

Enhance Payment Disposition Report

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionPaymentReport/GarmentDispositionPaymentReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionPaymentReport/IGarmentDispositionPaymentReportService.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/GarmentDispositionExpedition/GarmentDispositionExpeditionControllerTest.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/GarmentDispositionExpeditionController.cs

Add Filter External Purchase Order

Enhance-Payment-dispo-report-uat

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentPurchasingExpedition/GarmentPurchasingExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentPurchasingExpedition/IGarmentPurchasingExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/GarmentPurchasingExpeditionController.cs

update query get list retur purchasing

update get list retur purchasing

---

Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRealizationDocumentPOPDFTemplate.cs

Enhance - PDF VB Realization With PO - DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/VBRealizationDocumentPOPDFTemplate.cs

Enhance - PDF VB Realization With PO

---

Com.Danliris.Service.Finance.Accounting.Lib/AutoMapperProfiles/GarmentFinance/Adjustment/GarmentFinanceAdjustmentProfile.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentFinance/Adjustment/GarmentFinanceAdjustmentService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentFinance/Adjustment/IGarmentFinanceAdjustmentService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/JournalTransaction/JournalTransactionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/FinanceDbContext.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20230707004147_Create_Table_Garment_Adjustment.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20230707004147_Create_Table_Garment_Adjustment.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/GarmentFinance/Adjustment/GarmentFinanceAdjustmentItemModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/GarmentFinance/Adjustment/GarmentFinanceAdjustmentModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/PDFTemplates/GarmentFinanceAdjustmentPDFTemplate.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/GarmentFinance/Adjustment/GarmentFinanceAdjustmentItemViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/GarmentFinance/Adjustment/GarmentFinanceAdjustmentViewModel.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/GarmentFinance/Adjustment/GarmentFinanceAdjustmentControllerTest.cs
Com.Danliris.Service.Finance.Accounting.Test/DataUtils/GarmentFinance/Adjustment/GarmentFinanceAdjustmentDataUtil.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/GarmentFinance/Adjustment/BasicTests.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/GarmentFinance/Adjustment/GarmentFinanceAdjustmentController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Startup.cs

Create Gdjustment UAT

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentFinance/Reports/ValasDPPVATBankExpenditureNoteMonthlyRecap/ValasDPPVATBankExpenditureNoteMonthlyRecapService.cs
Com.Danliris.Service.Finance.Accounting.Test/Com.Danliris.Service.Finance.Accounting.Test.csproj

Enhance-Jurnal_Pengelauran-Kas-Valas | UAT

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentFinance/Reports/ValasDPPVATBankExpenditureNoteMonthlyRecap/ValasDPPVATBankExpenditureNoteMonthlyRecapService.cs
Com.Danliris.Service.Finance.Accounting.Test/Com.Danliris.Service.Finance.Accounting.Test.csproj

Enhance-Jurnal_Pengelauran-Kas-Valas | Dev

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/VBStatusReport/IVBStatusReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/VBStatusReport/VBStatusReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/FormDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/VBRealizationWithPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/IVBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/ReportDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentNonPOFormDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentWithPOFormDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20240318084631_enhance-vb-docs-and-vb-realization.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20240318084631_enhance-vb-docs-and-vb-realization.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20240418083028_Add-Column-VB-Realization-Expedition.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20240418083028_Add-Column-VB-Realization-Expedition.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRealizationDocument/VBRealizationDocumentModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRequestDocument/VBRequestDocumentModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/VBExpeditionRealizationReport/VBExpeditionRealizationReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/VBRealizationDocumentNonPO/VBRealizationDocumentNonPOViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/VBStatusReport/VBStatusReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/VBRealizationDocumentExpedition/VBRealizationExpeditionControllerTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/VBStatusReport/VBStatusReportControllerTest.cs
Com.Danliris.Service.Finance.Accounting.Test/DataUtils/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionDataUtil.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionServiceTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/VBStatusReport/VBStatusReportServiceTest.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/VBRealizationExpeditionController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/VBStatusReport/VBStatusReportController.cs

Enhance
VB Approval Cashier
VB Acceptance
Report Status VB
Report Expedisi Realisasi VB

Enhance VB Approval, Acceptance & Report | DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/VBRealizationDocumentNonPO/VBRealizationDocumentNonPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentNonPODto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentWithPODto.cs

Update Service & ViewMocel - dev

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/IVBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/VBRealizationDocumentExpedition/VBRealizationExpeditionControllerTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionServiceTest.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/VBRealizationExpeditionController.cs

enhance-report-expedisi-realisasi-vb-dev

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/VBRealizationDocumentNonPO/VBRealizationDocumentNonPOService.cs

Fix reading data from VB Document

Enhance VB Realization - DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/VBStatusReport/IVBStatusReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/VBRealizationDocumentNonPO/VBRealizationDocumentNonPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/VBStatusReport/VBStatusReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/FormDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/VBRealizationWithPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/IVBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/ReportDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentNonPODto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentNonPOFormDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentWithPODto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRequestDocument/VBRequestDocumentWithPOFormDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20240318084631_enhance-vb-docs-and-vb-realization.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20240318084631_enhance-vb-docs-and-vb-realization.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20240418083028_Add-Column-VB-Realization-Expedition.Designer.cs
Com.Danliris.Service.Finance.Accounting.Lib/Migrations/20240418083028_Add-Column-VB-Realization-Expedition.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRealizationDocument/VBRealizationDocumentModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRequestDocument/VBRequestDocumentModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/VBExpeditionRealizationReport/VBExpeditionRealizationReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/VBRealizationDocumentNonPO/VBRealizationDocumentNonPOViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/VBStatusReport/VBStatusReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/VBRealizationDocumentExpedition/VBRealizationExpeditionControllerTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Controllers/VBStatusReport/VBStatusReportControllerTest.cs
Com.Danliris.Service.Finance.Accounting.Test/DataUtils/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionDataUtil.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/VBRealizationDocumentExpedition/VBRealizationDocumentExpeditionServiceTest.cs
Com.Danliris.Service.Finance.Accounting.Test/Services/VBStatusReport/VBStatusReportServiceTest.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/VBRealizationExpeditionController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/VBStatusReport/VBStatusReportController.cs

Add Column Email,Phone Number, Name

Enhance vb realization - PRD

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/CashierReport/ICashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/CashierVBRealizationReport/ICashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierReport/CashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierVBRealizationReport/CashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Helpers/Excel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierReport/CashierReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierVBRealizationReport/CashierVBRealizationReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/CashierReport/CashierReportController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/CashierVBRealizationReport/CashierVBRealizationReportController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/VBRealizationExpeditionController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Startup.cs

Create-Report=Cashier
- VB Request Document
- VB Realization

2024/#16/Create-Report=Cashier-VB-And -Realization-VB - DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/UnitPaymentOrderDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/VBRealizationWithPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Com.Danliris.Service.Finance.Accounting.Lib.csproj

Add formula ispaytax & ispayvat

2024\#16\Enhance-VB-Realization-With-PO - DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/CashierReport/ICashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/CashierVBRealizationReport/ICashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierReport/CashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierVBRealizationReport/CashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/UnitPaymentOrderDto.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/VBRealizationDocument/VBRealizationWithPOService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Com.Danliris.Service.Finance.Accounting.Lib.csproj
Com.Danliris.Service.Finance.Accounting.Lib/Helpers/Excel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierReport/CashierReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierVBRealizationReport/CashierVBRealizationReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/CashierReport/CashierReportController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/CashierVBRealizationReport/CashierVBRealizationReportController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/VBRealizationExpeditionController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Startup.cs

Create Repoort Kasir Permohoanan VB & Realisasi VB
Update Formula for Vb Realization (Garment)

2024/#16/Enhance VB Realization With PO - UAT

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierReport/CashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierVBRealizationReport/CashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/Helpers/Excel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierReport/CashierReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierVBRealizationReport/CashierVBRealizationReportViewModel.cs

Enhance-Report-Cashier-UAT

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierReport/CashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierVBRealizationReport/CashierVBRealizationReportService.cs

2024/#17/Enhance-Cashier-Report - DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/Models/VBRealizationDocument/VBRealizationDocumentExpenditureItemModel.cs

2024/#17/Update Mapping Model - DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/DPPVATBankExpenditureNote/DPPVATBankExpenditureNoteService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentInvoicePurchasingDisposition/GarmentInvoicePurchasingDispositionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/CashierReport/ICashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/CashierVBRealizationReport/ICashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierReport/CashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierVBRealizationReport/CashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierReport/CashierReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierVBRealizationReport/CashierVBRealizationReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/CashierReport/CashierReportController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/CashierVBRealizationReport/CashierVBRealizationReportController.cs

2024/#18/Enahnce Report Cashier - DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/DPPVATBankExpenditureNote/DPPVATBankExpenditureNoteService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentInvoicePurchasingDisposition/GarmentInvoicePurchasingDispositionService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/CashierReport/ICashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Interfaces/CashierVBRealizationReport/ICashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierReport/CashierReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/Services/CashierVBRealizationReport/CashierVBRealizationReportService.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierReport/CashierReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/CashierVBRealizationReport/CashierVBRealizationReportViewModel.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/CashierReport/CashierReportController.cs
Com.Danliris.Service.Finance.Accounting.WebApi/Controllers/v1/CashierVBRealizationReport/CashierVBRealizationReportController.cs

Add Filer Approved By
Modify DPP & PPN - Disposition

2024/#19/Enhance Report Cashier - PRD

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionExpedition/GarmentDispositionExpeditionService.cs

2024/#22/Enhance Dispo Payment Invoice - DEV

---

Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionExpedition/GarmentDispositionExpeditionService.cs

2024/#22/Enhance Dispo  Payment  Invoice - PRD
